apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    {{- include "bot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongo
  selector:
    {{- include "bot.selectorLabels" . | nindent 4 }}
